baseURL = "https://wurbina.com/"
languageCode = "en-us"
title = "Warren's Blog"
theme = "ananke"

[params]
  github = "https://github.com/WarrenU"
  linkedin = "https://www.linkedin.com/in/urbinawarren/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
