baseURL="https://wurbina.com/"
publishDir="public"
languageCode="en-us"
title="Warren's Blog"
theme="gohugo-theme-ananke"
SectionPagesMenu="main"
defaultLayout="post"

[params]
  github="https://github.com/WarrenU"
  linkedin="https://www.linkedin.com/in/urbinawarren/"
  pluralizeListTitles=false
