baseURL = 'https://warrenu.github.io'
languageCode = 'en-us'
title = "Warren's Blog"
theme = 'ananke'

[menu]
  [[menu.main]]
  identifier = "resume"
  name = "Resume"
  url = "/docs/warren-urbina-resume.pdf"
  weight = 10
